# Generated by Django 4.2.4 on 2023-08-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_problem', '0002_alter_elevator_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='floor_numbers',
            field=models.TextField(default='0'),
        ),
    ]
