# Generated by Django 4.2.4 on 2023-08-09 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_problem', '0003_elevator_floor_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elevator',
            name='floor_numbers',
        ),
        migrations.CreateModel(
            name='ElevatorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_floor', models.IntegerField()),
                ('request_status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete')], default='pending', max_length=8)),
                ('lift_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='elevator_problem.elevator')),
            ],
        ),
    ]
